platform :ios, '8.0'



target 'PLMediaStreamingKitDemo' do
  pod "PLMediaStreamingKit", :path => "../"
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Masonry', '1.0.1'
end

target 'PLBroadcastExtension' do
  pod "PLMediaStreamingKit", :path => "../"
end

target 'PLBroadcastExtensionSetupUI' do
  pod "PLMediaStreamingKit", :path => "../"
end