source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'PLMediaStreamingKitDemo' do
  pod "PLMediaStreamingKit", :path => "../"
   pod 'Fabric', '1.6.11'
  pod 'Crashlytics', '3.8.4'
  pod 'Masonry', '1.0.2'
end
